name: 'Hello World Action'
description: 'Hello world'
inputs:
  user_name:  # ID parametru
    description: 'Jméno uživatele'
    required: true
    default: 'World'
outputs:
  text_greeting: # Název výstupu pro volající workflow
    description: 'Vygenerovaný pozdrav'
    value: ${{ steps.pozdrav.outputs.text_pozdravu }} # Odkaz na id: pozdrav
runs:
  using: 'composite'
  steps:
    - id: pozdrav
      run: echo "text_pozdravu='Hello ${{ inputs.user_name }}!'" >> $GITHUB_OUTPUT
      shell: bash
