name: Ukázka předání multiline outputu mezi kroky

on: 
  workflow_dispatch:

jobs:
  priklad-outputu:
    runs-on: ubuntu-latest
    steps:

      # 1. Krok: Vytvoření multiline outputu
      - name: Create multiline output
        id: create-multiline-output # Toto ID používáš pro odkazování
        run: |
          echo "multi_out<<EOF" >> $GITHUB_OUTPUT
          echo -e "\nPrvní řádek" >> $GITHUB_OUTPUT
          echo "Druhý řádek" >> $GITHUB_OUTPUT
          echo "Třetí řádek" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 2. Krok: Použití multiline outputu
      - name: Use multiline output
        run: |
          echo "Multiline output z předchozího stepu create-multiline-output: ${{ steps.create-multiline-output.outputs.multi_out }}"
