name: Ukázka Outputu mezi kroky

on: 
  workflow_dispatch:

jobs:
  priklad-outputu:
    runs-on: ubuntu-latest
    steps:

      # 1. Krok: Vytvoření outputu
      - name: Získání času
        id: hello # Toto ID používáš pro odkazování
        run: |
          echo "username='JoeShmoe'" >> $GITHUB_OUTPUT

      # 2. Krok: Použití outputu
      - name: Výpis času
        run: |
          echo "Jméno uživatele je: ${{ steps.hello.outputs.username }}"
