name: Print env secret ENV

on:
  workflow_dispatch:

jobs:
  print-secret-ENV:
    runs-on: ubuntu-latest
    environment: tst
    steps:
      - name: Print env secret ENV
        if: ${{ secrets.ENV == 'env/deva' }}
        run: echo "Environment: env-deva"
