name: Print env secret ENV

on:
  workflow_dispatch:

jobs:
  print-secret-ENV:
    name: print-secret-ENV
    runs-on: ubuntu-latest
    environment: env/deva
    steps:
      - name: Print env secret ENV
        env:
          MY_SECRET: ${{ secrets.ENV }}
        run: |
          if [ "$MY_SECRET" = "env/deva" ]; then
            echo "Environment: env-deva"
          else
            echo "Secret se neshoduje nebo je prázdný"
          fi
