name: Test Action
on: 
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Akce pozdrav z action
    steps:
      - uses: actions/checkout@v3
      - name: Spustit vlastni action
        id: hello
        # Odkazuje na akci v aktualnim repozitari
        uses: ./ 
      - name: Získat string pozdravu z action
        run: | 
          echo "Pozdrav byl: ${{ steps.hello.outputs.text_greeting }}"
